define([], function() {
    return {
        2003: {
            expenses: {
                "Administrative Expense": 12433,
                "Professional Fees": 3313,
                "Insurance": 56341,
                "Management": 30418,
                "Landscaping, Grounds, and Drainage": 122745,
                "Supplies": 560,
                "Water": 2429,
                "Interest Expense": 11938,
                "Payroll and Related Expenses": 9973,
                "Electrical Repairs": 0,
                "Plumbing": 608,
                "Exterminator": 2987,
                "Speed Bumps": 0,
                "Cleaning": 4938,
                "Building Repairs": 5530,
                "Pool Expenses": 6064,
                "Alarm Monitoring": 996,
                "Utilities": 8565,
                "Telephone": 1318,
                "Licenses": 61,
                "Provision for State Income Taxes": 33
            },
            income: {
                "Interest Income": 144,
                "Other Income": 353,
                "Common Charges (Note 1)": 253417,
                "Total Revenues": 253914,
                "Total Expenses": 281250,
                "Net Profit (Loss)": 27336
            }
        },
        2004: {
            expenses: {
                "Administrative Expense": 8898,
                "Professional Fees": 5209,
                "Insurance": 59614,
                "Management": 31642,
                "Landscaping, Grounds, and Drainage": 148355,
                "Supplies": 263,
                "Water": 2259,
                "Interest Expense": 11186,
                "Payroll and Related Expenses": 7549,
                "Electrical Repairs": 1100,
                "Plumbing": 489,
                "Exterminator": 2592,
                "Speed Bumps": 3819,
                "Cleaning": 6114,
                "Building Repairs": 2848,
                "Pool Expenses": 7793,
                "Alarm Monitoring": 1399,
                "Utilities": 8133,
                "Telephone": 1398,
                "Licenses": 250,
                "Provision for State Income Taxes": 89
            },
            income: {
                "Interest Income": 55,
                "Other Income": 300,
                "Common Charges (Note 1)": 331735,
                "Total Revenues": 332090,
                "Total Expenses": 310999,
                "Net Profit (Loss)": 21091
            }
        },
        2005: {
            expenses: {
                "Administrative Expense": 7517,
                "Professional Fees": 3393,
                "Insurance": 74282,
                "Management": 32591,
                "Landscaping, Grounds, and Drainage": 136659,
                "Supplies": 591,
                "Water": 4587,
                "Interest Expense": 9652,
                "Payroll and Related Expenses": 10182,
                "Electrical Repairs": 1924,
                "Plumbing": 972,
                "Exterminator": 3426,
                "Speed Bumps": 2635,
                "Cleaning": 7112,
                "Building Repairs": 2612,
                "Pool Expenses": 8736,
                "Gutters and leaders": 3277,
                "Alarm Monitoring and repairs": 5510,
                "Utilities": 9558,
                "Telephone": 1554,
                "Licenses": 250,
                "Provision for State Income Taxes": 31
            },
            income: {
                "Interest Income": 361,
                "Other Income": 672,
                "Assessments": 40800,
                "Common Charges (Note 1)": 358160,
                "Total Revenues": 399993,
                "Total Expenses": 337051,
                "Net Profit (Loss)": 72942
            }
        },
        2006: {
            expenses: {
                "Administrative Expense": 7340,
                "Professional Fees": 2905,
                "Insurance": 76575,
                "Management": 33486,
                "Landscaping, Grounds, and Drainage": 179350,
                "Water": 2410,
                "Interest Expense": 9563,
                "Payroll and Related Expenses": 9338,
                "Electrical Repairs": 2370,
                "Plumbing": 822,
                "Exterminator": 2551,
                "Speed Bumps": 0,
                "Cleaning": 3286,
                "Building Repairs": 2329,
                "Pool Expenses": 3582,
                "Gutters and leaders": 4273,
                "Driveways": 14850,
                "Settlement costs": 8269,
                "Alarm Monitoring and repairs": 1080,
                "Utilities": 8868,
                "Telephone and cable": 1567,
                "Fencing": 0,
                "Masonry": 0,
                "Doors, locks & glass": 1836,
                "Licenses": 250,
                "Provision for State Income Taxes": 129
            },
            income: {
                "Interest Income": 1780,
                "Other Income": 0,
                "Settlement with Sponsor": 17770,
                "Common Charges (Note 1)": 387355,
                "Total Revenues": 406905,
                "Total Expenses": 377029,
                "Net Profit (Loss)": 29876
            }
        },
        2007: {
            expenses: {
                "Administrative Expense": 11680,
                "Professional Fees": 4799,
                "Insurance": 78819,
                "Management": 34576,
                "Landscaping, Grounds, and Drainage": 175462,
                "Water": 13179,
                "Interest Expense": 9384,
                "Payroll and Related Expenses": 11325,
                "Electrical Repairs": 1981,
                "Plumbing": 2478,
                "Exterminator": 2575,
                "Speed Bumps": 781,
                "Cleaning": 3780,
                "Building Repairs": 4222,
                "Pool Expenses": 6250,
                "Gutters and leaders": 13209,
                "Driveways": 0,
                "Settlement costs": 0,
                "Alarm Monitoring and repairs": 2720,
                "Utilities": 10338,
                "Telephone and cable": 1560,
                "Fencing": 4776,
                "Masonry": 11819,
                "Doors, locks & glass": 1613,
                "Licenses": 250,
                "Provision for State Income Taxes": 237
            },
            income: {
                "Interest Income": 2865,
                "Other Income": 328,
                "Settlement with Sponsor": 0,
                "Common Charges (Note 1)": 387355,
                "Total Revenues": 390548,
                "Total Expenses": 407813,
                "Net Profit (Loss)": 17265
            }
        },
        2008: {
            expenses: {
                "Administrative Expense": 7484,
                "Professional Fees": 2678,
                "Insurance": 78767,
                "Management": 35000,
                "Landscaping, Grounds, and Drainage": 167214,
                "Water": 3268,
                "Interest Expense": 9278,
                "Payroll and Related Expenses": 0,
                "Electrical Repairs": 3249,
                "Plumbing": 1481,
                "Exterminator": 2692,
                "Speed Bumps": 0,
                "Cleaning": 4027,
                "Building Repairs": 7743,
                "Pool Expenses": 15378,
                "Gutters and leaders": 6880,
                "Sprinklers": 6650,
                "Paint and plaster": 2895,
                "Alarm Monitoring and repairs": 1080,
                "Utilities": 10954,
                "Telephone and cable": 1535,
                "Fencing": 0,
                "Masonry": 3758,
                "Doors, locks & glass": 0,
                "Licenses": 640,
                "Provision for State Income Taxes": 3
            },
            income: {
                "Interest Income": 1844,
                "Other Income": 912,
                "Common Charges (Note 1)": 387355,
                "Total Revenues": 390111,
                "Total Expenses": 372654,
                "Net Profit (Loss)": 17457
            }
        },
        2009: {
            expenses: {
                "Administrative Expense": 5833,
                "Professional Fees": 2938,
                "Insurance": 65125,
                "Management": 36050,
                "Landscaping, Grounds, and Drainage": 149733,
                "Water": 4587,
                "Interest Expense": 9258,
                "Electrical Repairs": 5577,
                "Plumbing": 1438,
                "Exterminator": 2692,
                "Speed Bumps": 0,
                "Cleaning": 5233,
                "Building Repairs": 6839,
                "Pool Expenses": 24911,
                "Gutters and leaders": 10305,
                "Sprinklers": 2288,
                "Paint and plaster": 0,
                "Alarm Monitoring and repairs": 1392,
                "Utilities": 9228,
                "Telephone and cable": 2170,
                "Seal coating": 19165,
                "Masonry": 0,
                "Licenses": 250,
                "Provision for State Income Taxes": 215
            },
            income: {
                "Interest Income": 1806,
                "Other Income": 961,
                "Common Charges (Note 1)": 427584,
                "Total Revenues": 430351,
                "Total Expenses": 365227,
                "Net Profit (Loss)": 65124
            }
        },
        2010: {
            expenses: {
                "Administrative Expense": 5589,
                "Professional Fees": 4132,
                "Insurance": 84785,
                "Management": 37132,
                "Landscaping, Grounds, and Drainage": 164982,
                "Water": 10441,
                "Interest Expense": 9207,
                "Electrical Repairs": 4621,
                "Plumbing": 3542,
                "Exterminator": 2692,
                "Exercise Equipment": 5154,
                "Cleaning": 4820,
                "Building Repairs": 7173,
                "Pool Expenses": 19125,
                "Gutters and leaders": 10350,
                "Sprinklers": 4271,
                "Paint and plaster": 1083,
                "Alarm Monitoring and repairs": 1540,
                "Utilities": 9079,
                "Telephone and cable": 1763,
                "Seal coating": 5502,
                "Licenses": 310,
                "Provision for State Income Taxes": 290
            },
            income: {
                "Interest Income": 1655,
                "Other Income": 206,
                "Common Charges (Note 1)": 427584,
                "Total Revenues": 429445,
                "Total Expenses": 397583,
                "Net Profit (Loss)": 31862
            }
        },
        2011: {
            expenses: {
                "Administrative Expense": 4632,
                "Professional Fees": 13379,
                "Engineering": 27242,
                "Insurance": 88662,
                "Management": 38246,
                "Landscaping, Grounds, and Drainage": 197991,
                "Water": 6530,
                "Interest Expense": 8929,
                "Electrical Repairs": 12580,
                "Plumbing": 3785,
                "Exterminator": 2742,
                "Exercise Equipment": 1449,
                "Cleaning": 4922,
                "Building Repairs": 12963,
                "Pool Expenses": 22039,
                "Gutters and leaders": 6900,
                "Sprinklers": 10752,
                "Paint and plaster": 1717,
                "Alarm Monitoring and repairs": 1574,
                "Utilities": 7998,
                "Telephone and cable": 1583,
                "Seal coating": 0,
                "Licenses": 318,
                "Provision for State Income Taxes": 375
            },
            income: {
                "Interest Income": 862,
                "Other Income": 705,
                "Common Charges (Note 1)": 443904,
                "Total Revenues": 445471,
                "Total Expenses": 477308,
                "Net Profit (Loss)": 31837
            }
        },
        2012: {
            expenses: {
                "Administrative Expense": 3394,
                "Professional Fees": 21817,
                "Engineering": 86026,
                "Insurance": 75685,
                "Management": 38246,
                "Landscaping, Grounds, and Drainage": 166353,
                "Water": 6532,
                "Interest Expense": 8736,
                "Electrical Repairs": 3263,
                "Plumbing": 2326,
                "Exterminator": 2956,
                "Exercise Equipment": 1288,
                "Cleaning": 3092,
                "Building Repairs": 4259,
                "Pool Expenses": 21957,
                "Gutters and leaders": 6900,
                "Sprinklers": 0,
                "Paint and plaster": 0,
                "Alarm Monitoring and repairs": 2007,
                "Utilities": 7734,
                "Telephone and cable": 1704,
                "Licenses": 1060,
                "Provision for State Income Taxes": 375
            },
            income: {
                "Interest Income": 565,
                "Other Income": 5798,
                "Common Charges (Note 1)": 460224,
                "Total Revenues": 466587,
                "Total Expenses": 465710,
                "Net Profit (Loss)": 877
            }
        },
        2013: {
            expenses: {
                "Administrative Expense": 4499,
                "Professional Fees": 11950,
                "Engineering": 0,
                "Insurance": 100387,
                "Management": 38246,
                "Landscaping, Grounds, and Drainage": 179452,
                "Water": 8325,
                "Interest Expense": 10565,
                "Electrical Repairs": 6519,
                "Plumbing": 2617,
                "Exterminator": 2548,
                "Exercise Equipment": 1288,
                "Cleaning": 3988,
                "Building Repairs": 11408,
                "Pool Expenses": 23967,
                "Gutters and leaders": 8290,
                "Sprinklers": 4391,
                "Hill restoration": 622420,
                "Signage": 6815,
                "Power washing": 8041,
                "Alarm Monitoring and repairs": 1080,
                "Utilities": 7880,
                "Telephone and cable": 1853,
                "Licenses": 336,
                "Provision for State Income Taxes": 347
            },
            income: {
                "Interest Income": 323,
                "Assessments": 169548,
                "Other Income": 100,
                "Common Charges (Note 1)": 460224,
                "Total Revenues": 630195,
                "Total Expenses": 1067212,
                "Net Profit (Loss)": 437017
            }
        },
        2014: {
            expenses: {
                "Administrative Expense": 3481,
                "Professional Fees": 5672,
                "Engineering": 4185,
                "Insurance": 82795,
                "Management": 39401,
                "Landscaping, Grounds, and snow removal": 207758,
                "Water": 8960,
                "Interest Expense": 28517,
                "Electrical Repairs": 4717,
                "Plumbing": 7621,
                "Exterminator": 3365,
                "Exercise Equipment": 1396,
                "Cleaning": 3810,
                "Building Repairs": 5764,
                "Pool Expenses": 29150,
                "Gutters and leaders": 10600,
                "Sprinklers": 9073,
                "Hill restoration": 92423,
                "Signage": 0,
                "Power washing": 0,
                "Alarm Monitoring and repairs": 1889,
                "Utilities": 9418,
                "Telephone and cable": 2409,
                "Paving": 8783,
                "Mailbox replacement": 33827,
                "Licenses": 315,
                "Provision for State Income Taxes": 585
            },
            income: {
                "Interest Income": 543,
                "Assessments": 56890,
                "Other Income": 81,
                "Common Charges (Note 1)": 460224,
                "Total Revenues": 517738,
                "Total Expenses": 605914,
                "Net Profit (Loss)": 88176
            }
        },
        2015: {
            expenses: {
                "Administrative Expense": 4934,
                "Professional Fees": 2500,
                "Engineering": 0,
                "Insurance": 79501,
                "Management": 40189,
                "Landscaping, Grounds, and snow removal": 182945,
                "Water": 7043,
                "Interest Expense": 28756,
                "Electrical Repairs": 1774,
                "Plumbing": 1342,
                "Exterminator": 3119,
                "Exercise Equipment": 1315,
                "Cleaning": 3496,
                "Building Repairs": 5418,
                "Pool Expenses": 26119,
                "Gutters and leaders": 3450,
                "Sprinklers": 14039,
                "Hill restoration": 0,
                "Fencing": 10294,
                "Pool resurfacing": 18919,
                "Alarm Monitoring and repairs": 2329,
                "Utilities": 8028,
                "Telephone and cable": 2107,
                "Paving": 6400,
                "Mailbox replacement": 0,
                "Licenses": 315,
                "Provision for State Income Taxes": 585
            },
            income: {
                "Interest Income": 458,
                "Assessments": 58900,
                "Expense reimbursement": 32449,
                "Other Income": 645,
                "Common Charges (Note 1)": 476554,
                "Total Revenues": 568996,
                "Total Expenses": 454917,
                "Net Profit (Loss)": 114079
            }
        },
        2016: {
            expenses: {
                "Administrative Expense": 3848,
                "Professional Fees": 2800,
                "Engineering": 4600,
                "Insurance": 91918,
                "Management": 40993,
                "Landscaping, Grounds, and snow removal": 185248,
                "Water": 13084,
                "Interest Expense": 26167,
                "Electrical Repairs": 5074,
                "Plumbing": 1827,
                "Exterminator": 3417,
                "Exercise Equipment": 1288,
                "Cleaning": 6013,
                "Building Repairs": 8643,
                "Pool Expenses": 24764,
                "Gutters and leaders": 6900,
                "Sprinklers": 0,
                "Fencing": 9105,
                "Pool resurfacing": 0,
                "Alarm Monitoring and repairs": 103,
                "Utilities": 8170,
                "Telephone and cable": 2386,
                "Paving": 4778,
                "Drainage": 5340,
                "Licenses": 315,
                "Provision for State Income Taxes": 628
            },
            income: {
                "Interest Income": 476,
                "Assessments": 57400,
                "Expense reimbursement": 0,
                "Other Income": 104,
                "Common Charges (Note 1)": 491504,
                "Total Revenues": 549484,
                "Total Expenses": 457409,
                "Net Profit (Loss)": 92075
            }
        },
        2017: {
            expenses: {
                "Administrative Expense": 4705,
                "Professional Fees": 2600,
                "Engineering": 300,
                "Insurance": 95220,
                "Management": 41813,
                "Landscaping, Grounds, and snow removal": 193471,
                "Water": 14040,
                "Interest Expense": 23282,
                "Electrical Repairs": 2256,
                "Plumbing": 1255,
                "Exterminator": 2692,
                "Exercise Equipment": 2003,
                "Cleaning": 5658,
                "Building Repairs": 9723,
                "Pool Expenses": 24432,
                "Gutters and leaders": 6900,
                "Fencing": 17306,
                "Alarm Monitoring and repairs": 114,
                "Utilities": 8224,
                "Telephone and cable": 2521,
                "Paving": 4724,
                "Drainage": 0,
                "Licenses": 315,
                "Provision for State Income Taxes": 640
            },
            income: {
                "Interest Income": 462,
                "Assessments": 65725,
                "Other Income": 332,
                "Common Charges (Note 1)": 509184,
                "Total Revenues": 575703,
                "Total Expenses": 464194,
                "Net Profit (Loss)": 111509
            }
        },
        2018: {
            expenses: {
                "Office expenses": 4903,
                "Professional Fees": 2951,
                "Management": 42231,
                "Water": 12347,
                "Utilities": 10291,
                "Insurance": 107288,
                "Landscaping, Grounds, & Snow": 222359,
                "Equipment": 7457,
                "Plumbing, Sewers, and Drains": 15602,
                "Exterminating": 2468,
                "Gutters": 6900,
                "Pool Expenses": 36861,
                "Electrical": 4041,
                "Paving": 6362,
                "Janitorial": 5867,
                "Fence": 14594,
                "Other repairs and maintenance": 6999,
                "Corporate Taxes": 642
            },
            income: {
                "Assessments": 81081,
                "HOA dues": 509184,
                "Interest income": 1879,
                "Other revenue": 346,
                "Total Revenue": 592490,
                "Total Expenses": 510163,
                "Income from operations": 82327,
                "Interest expense on loan": 20317,
                "Major repairs - Drainage": 25448,
                "Major repairs - Water Meter Pit": 13300,
                "Net Profit (Loss)": 23262
            }
        },
        2019: {
            expenses: {
                "Office expenses": 6278,
                "Professional Fees": 3001,
                "Management": 43076,
                "Water": 9395,
                "Utilities": 10315,
                "Insurance": 108901,
                "Landscaping, Grounds, & Snow": 211999,
                "Equipment": 542,
                "Plumbing, Sewers, and Drains": 295,
                "Exterminating": 2925,
                "Gutters": 6900,
                "Pool Expenses": 30127,
                "Electrical": 1556,
                "Paving": 3194,
                "Janitorial": 10293,
                "Fence": 12151,
                "Other repairs and maintenance": 11628,
                "Corporate Taxes": 643
            },
            income: {
                "Assessments": 82528,
                "HOA dues": 541824,
                "Interest income": 3428,
                "Other revenue": 0,
                "Total Revenue": 627780,
                "Total Expenses": 473219,
                "Income from operations": 154561,
                "Interest expense on loan": 17189,
                "Major repairs - Drainage": 0,
                "Major repairs - Lighting Project": 8776,
                "Major repairs - Water Meter Pit": 0,
                "Major repairs - Pool furniture": 17018,
                "Net Profit (Loss)": 111578
            }
        },
        2020: {
            expenses: {
                "Office expenses": 6244,
                "Professional Fees": 3201,
                "Management": 44368,
                "Water": 14491,
                "Utilities": 8822,
                "Insurance": 110011,
                "Landscaping, Grounds, & Snow": 223891,
                "Equipment": 325,
                "Plumbing, Sewers, and Drains": 639,
                "Exterminating": 2717,
                "Gutters": 3450,
                "Pool Expenses": 21543,
                "Electrical": 0,
                "Paving": 13276,
                "Janitorial": 1465,
                "Fence": 14275,
                "Other repairs and maintenance": 12705,
                "Corporate Taxes": 645
            },
            income: {
                "Assessments": 82528,
                "HOA dues": 574464,
                "Interest income": 1874,
                "Other revenue": 3704,
                "Total Revenue": 662570,
                "Total Expenses": 482068,
                "Income from operations": 180502,
                "Interest expense on loan": 13933,
                "Major repairs - Lighting Project": 1840,
                "Major repairs - Pool furniture": 0,
                "Net Profit (Loss)": 164729
            }
        },
        2021: {
            expenses: {
                "Office expenses": 8143,
                "Professional Fees": 11023,
                "Management": 44810,
                "Water": 15824,
                "Utilities": 11210,
                "Insurance": 96476,
                "Landscaping, Grounds, & Snow": 253273,
                "Equipment": 0,
                "Plumbing, Sewers, and Drains": 4000,
                "Exterminating": 2717,
                "Gutters": 6900,
                "Pool Expenses": 22626,
                "Electrical": 929,
                "Paving": 5067,
                "Janitorial": 4065,
                "Fence": 30226,
                "Other repairs and maintenance": 10945,
                "Corporate Taxes": 647
            },
            income: {
                "Assessments": 82528,
                "HOA dues": 598944,
                "Interest income": 558,
                "Other revenue": 0,
                "Total Revenue": 682030,
                "Total Expenses": 528881,
                "Income from operations": 153149,
                "Interest expense on loan": 10415,
                "Major repairs - Lighting Project": 0,
                "Net Profit (Loss)": 142734
            }
        },
        2022: {
            expenses: {
                "Office expenses": 1738,
                "HOA dues expense": 449232,
                "HOA assessments": 58880,
                "Professional fees": 3333,
                "Utilities": 626,
                "Insurance": 4159,
                "Sprinklers": 9428,
                "Powerwashing & Deck staining": 13579,
                "Window wells": 137210,
                "Walkway": 0,
                "Roof": 7143,
                "Other repairs and maintenance": 2242,
                "Corporate Taxes": 650
            },
            income: {
                "Common Charges": 112990,
                "Assessments": 41240,
                "Assessments - Road Fund": 17640,
                "Late Fees": 1700,
                "Chargeback Income": 195,
                "Interest Income": 3025,
                "HOA dues income": 449232,
                "Other revenue": 978,
                "Total revenue": 627000,
                "Total expenses": 688220,
                "Income from operations": 61220,
                "Net Profit (Loss)": 61220
            }
        }
    };
});